# Generated by Django 5.2.8 on 2025-11-24 11:32

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('user_type', models.CharField(choices=[('buyer', 'Property Buyer'), ('agent', 'Real Estate Agent'), ('admin', 'Administrator')], default='buyer', help_text='Designates the role of the user in the system', max_length=10, verbose_name='user type')),
                ('phone_number', models.CharField(blank=True, help_text="User's contact phone number", max_length=15, verbose_name='phone number')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the user has been verified. For agents, this means admin approval.', verbose_name='verified status')),
                ('license_number', models.CharField(blank=True, help_text='Official real estate license number for verified agents', max_length=50, verbose_name='real estate license number')),
                ('agency_name', models.CharField(blank=True, help_text='Name of the real estate agency the agent works for', max_length=100, verbose_name='agency name')),
                ('years_experience', models.PositiveIntegerField(default=0, help_text='Number of years working in real estate industry', verbose_name='years of experience')),
                ('bio', models.TextField(blank=True, help_text='Professional biography or description', verbose_name='professional bio')),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_pics/%Y/%m/%d/', verbose_name='profile picture')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['user_type', 'is_verified'], name='users_user_user_ty_fb1442_idx'), models.Index(fields=['date_joined'], name='users_user_date_jo_064c8f_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
